### ISSUE TITLE
Watchtower schedule follows golangs chron syntax

### ISSUE THREAD

**Issue by LucaMH** [Haxxnet/Compose-Examples#1]
Hi,

first of all, cool repo!

regarding this line:
https://github.com/Haxxnet/Compose-Examples/blob/16ff828b9e668698a2e7dc7f4379ca43a50a28e7/watchtower/docker-compose.yml#L15
Watchtower is written in go which uses 6 fields instead of 5. (stepped into this and lost a good hour when i first used watchtower 😎....)
https://crontab.guru/ is not supporting that.
See https://containrrr.dev/watchtower/arguments/#scheduling or https://pkg.go.dev/github.com/robfig/cron@v1.2.0#hdr-CRON_Expression_Format

**Comment by l4rm4nd** [comment]
Thanks for pointing out! Gladly, the compose file already defined the correct cron syntax.

Therefore, I just changed the comment with the reference to crontab.guru.

See fix https://github.com/Haxxnet/Compose-Examples/commit/6ef65f66bf1032538d5e8c8f98b4f293fc38a9bc
