### ISSUE TITLE
Questions about creating networks and global environment variables

### ISSUE THREAD

**Issue by sofakng** [Haxxnet/Compose-Examples#18]
Hey, thanks for these great examples (and for answers so many questions on Reddit), but I had another two questions:

1) How do you create your Docker networks?  (ie. proxy network)

In your Traefik example, it looks you like you are using an external 'proxy' network.  Do you manually create this using the command-line or use a more convenient way?  (ie. script)

Also, the Traefik example specifies host.docker.internal as 172.17.0.1 but that's the Docker system bridge network.  Should this be 172.18.0.1 (or whatever your created network ip address is?)

2) Where do you define your global environment variables?  (ie. ${DOCKER_VOLUME_STORAGE})

I know you can create a .env file inside each Docker compose folder but that's a ton of duplication.  I'm thinking you have to define it inside your user profile but that's a bit messy?

Thanks for the help!

**Comment by l4rm4nd** [comment]
> How do you create your Docker networks? (ie. proxy network)

Basically just a matter of:

````
docker network create proxy
````

> Where do you define your global environment variables? (ie. ${DOCKER_VOLUME_STORAGE})

I personally do not change it at all, as its my default storage path. 

However, if you want to change it, you would typically export the env via your terminal. As this would be an annoying manual task each time, I recommend setting it either on your bash profile or `.bash_rc`.
