### ISSUE TITLE
Chevereto

### ISSUE THREAD

**Issue by rodber** [Haxxnet/Compose-Examples#24]
Hello,

There are some missing parts in the Chevereto readme.

https://github.com/Haxxnet/Compose-Examples/tree/main/examples/chevereto

The path you mention is configurable, by default it is at `images/_assets`. For no reason you should use 777 permission, try chowning the path to www-data or at least use 755.

Hope it helps.

**Comment by l4rm4nd** [comment]
Hi @rodber ,

thanks for the info. I've adjusted the chmod permissions to 775. Chmod to www-data was already applied.

Only affects bind mount volumes though.
