### ISSUE TITLE
Update README with the new dir title

### ISSUE THREAD

**Issue by pelumbum** [Haxxnet/Compose-Examples#25]
In https://github.com/Haxxnet/Compose-Examples/blob/main/README.md?plain=1#L402 the link points to [examples/firefly-iii](https://github.com/Haxxnet/Compose-Examples/blob/main/examples/firefly-iii), though the actual name of the directory is [examples/firefly](https://github.com/Haxxnet/Compose-Examples/blob/main/examples/firefly)

**Comment by l4rm4nd** [comment]
Good catch. Thanks!
